[package]
name = "orochimaru"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "orochimaru"
path = "src/main.rs"

[features]

[dependencies]
ecvrf = { version = "1.0.0", path="./ecvrf" }
tiny-keccak = { version = "2.0.2", default-features = false, features=["keccak"] }
log = "0.4.17"
env_logger = "0.9.0"
hex = "0.4.3"
tokio = { version = "1.21.2", features = ["full"] }
hyper = { version = "1.0.0-rc.1", features = ["server", "client", "http1", "http2"] }
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
serde = "1.0.147"
hmac = "0.12.1"
serde_json = "1.0.87"
bytes = "1.3.0"
http-body-util = "0.1.0-rc.1"
dotenv = "0.15.0"
# pallet-evm = "5.0.0"
# primitive-types = "0.12.1"